name: "NGinx reverse proxy"
description: "NGinx web reverse proxy with enabled docker tcp protocol forwarding."
url: "https://github.com/InuSasha/hassio-addons/tree/master/hassio-nginx"

version: "1.0.6"
slug: "nginx"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# needs original source ip
host_network: true
docker_api: true

map:
  - ssl
