name: "NGinx reverse proxy"
description: "NGinx web reverse proxy with enabled docker tcp protocol forwarding."
url: "https://github.com/InuSasha/hassio-nginx"
version: "1.0.2"
slug: "nginx"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  80/tcp: 80
  443/tcp: 443
  2376/tcp: 2376

docker_api: true