name: "Music Player Daemon"
description: "Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol."
url: "https://github.com/InuSasha/hassio-mpd"
version: "0.23.13-3"
slug: "mpd"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  6600/tcp: 6600
audio: true
