name: "Postgres 15"
description: "A sophisticated object-relational DBMS, version 15."
url: "https://github.com/InuSasha/hassio-postgresql15"
version: "1.0.0"
slug: "postgresql15"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  5432/tcp: 5432
